Canta_dark = {
        "View Background" : "#272a2a",
        "View Text" : "#eaeaea",
        "Window Background" : "#272a2a",
        "Window Text" : "#eaeaea",
        "Button Background" : "#3b4342",
        "Button Text" : "#eaeaea",
        "Selection Background" : "#00ce99",
        "Selection Text" : "#ffffff",
        "Selection Inactive Text" : "#8ecbe9",
        "Inactive Text" : "#999999",
        "Active Text" : "#ff80e0",
        "Link Text" : "#4285f4",
        "Visited Text" : "#e040fb",
        "Focus Decoration" : "#ffac00",
        "Tooltip Background" : "#272a2a",
        "Tooltip Text" : "#dddddd",
        "Active Titlebar" : "#36383e",
        "Active Titlebar Text" : "#36383e",
        "Active Titlebat Secondary" : "#36383e",
        "Inactive Titlebar" : "#3e4147",
        "Inactive Titlebar Text" : "#787878",
        "Inactive Titlebar Secondary" : "#43474d",
}
